name: Build documentation pages

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build-and-run:
    name: Build documentation pages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create conda environment
      uses: goanpeca/setup-miniconda@v1
      with:
         activate-environment: geocat-examples
         environment-file: conda_environment.yml
    - name: Build sphinx docs
      shell: bash -l {0}
      run: |
        conda info
        conda list
        make html
    - name: Verify that a webpage exists for each script
      shell: bash -l {0}
      run: |
        rm _build/html/gallery/Polygons/NCL_polyg_4.html
        missing=0; for pyscript in $(find Plots -name "NCL_*.py" | cut -d/ -f2- | xargs); do html=_build/html/gallery/${pyscript%.py}.html; if [ ! -e ${html} ]; then missing=$(($missing + 1)); echo "No webpage generated for example ${pyscript}"; fi; done; echo $missing; exit ${missing}
